# See: http://about.travis-ci.org/docs/user/build-configuration/
# See: https://github.com/satooshi/php-coveralls

language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cp conf/phpunit-dist.xml conf/phpunit.xml
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --configuration conf/phpunit.xml
  - php vendor/bin/phpcs --standard=PSR2 src/ tests/ -v
  - php vendor/bin/phpmd src/ text codesize,design,unusedcode,naming,controversial || true

after_script:
  - php vendor/bin/coveralls -v

notifications:
  on_success: always
  on_failure: always
