SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `supervisor` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `supervisor` ;

-- -----------------------------------------------------
-- Table `supervisor`.`EDE_USER`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `supervisor`.`EDE_USER` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FIRSTNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `LASTNAME` VARCHAR(45) NULL DEFAULT NULL ,
  `EMAIL` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `IS_ADMIN` INT(11) NOT NULL ,
  `DATE_INSERT` TIMESTAMP NULL DEFAULT NULL ,
  `DATE_UPDATE` TIMESTAMP NULL DEFAULT NULL ,
  PRIMARY KEY (`USER_ID`) )
ENGINE = InnoDB
AUTO_INCREMENT = 582
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `supervisor`.`EDE_PROJECT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `supervisor`.`EDE_PROJECT` (
  `PROJECT_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `GROUP` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `OWNER_ID` INT(11) NOT NULL ,
  `CREATOR_ID` INT(11) NOT NULL ,
  `DATE_INSERT` TIMESTAMP NULL DEFAULT NULL ,
  `DATE_UPDATE` TIMESTAMP NULL DEFAULT NULL ,
  PRIMARY KEY (`PROJECT_ID`) ,
  INDEX `FK_PROJECT_USER` (`CREATOR_ID` ASC) ,
  INDEX `FK_PROJECT_USER2` (`OWNER_ID` ASC) ,
  CONSTRAINT `FK_PROJECT_USER`
    FOREIGN KEY (`CREATOR_ID` )
    REFERENCES `supervisor`.`EDE_USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJECT_USER2`
    FOREIGN KEY (`OWNER_ID` )
    REFERENCES `supervisor`.`EDE_USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `supervisor`.`EDE_PROJECT_CONFIGURATION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `supervisor`.`EDE_PROJECT_CONFIGURATION` (
  `PROJECT_CONFIGURATION_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PROJECT_ID` INT(11) NOT NULL ,
  `CREATOR_ID` INT(11) NOT NULL ,
  `REVISION` INT(11) NOT NULL ,
  `STATUS` ENUM('ACTIVE','INACTIVE') NULL DEFAULT 'ACTIVE' ,
  `CONFIGURATION` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `ENVIRONMENT` TEXT NULL DEFAULT NULL ,
  `EXTERNAL_PROPERTY` TEXT NULL DEFAULT NULL ,
  `DATE_INSERT` TIMESTAMP NULL DEFAULT NULL ,
  `DATE_UPDATE` TIMESTAMP NULL DEFAULT NULL ,
  PRIMARY KEY (`PROJECT_CONFIGURATION_ID`) ,
  INDEX `PROJECT_ID` (`PROJECT_ID` ASC) ,
  INDEX `FK_PROJECT_CONFIGURATION_USER` (`CREATOR_ID` ASC) ,
  INDEX `FK_PROJECT_CONFIGURATION_PROJECT` (`PROJECT_ID` ASC) ,
  CONSTRAINT `FK_PROJECT_CONFIGURATION_USER`
    FOREIGN KEY (`CREATOR_ID` )
    REFERENCES `supervisor`.`EDE_USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJECT_CONFIGURATION_PROJECT`
    FOREIGN KEY (`PROJECT_ID` )
    REFERENCES `supervisor`.`EDE_PROJECT` (`PROJECT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `supervisor`.`EDE_DEPLOY_QUEUE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `supervisor`.`EDE_DEPLOY_QUEUE` (
  `DEPLOY_QUEUE_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PROJECT_ID` INT(11) NOT NULL ,
  `PROJECT_CONFIGURATION_ID` INT(11) NOT NULL ,
  `ENVIRONMENT` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `PARAMETERS` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `EXTERNAL_PROPERTY` TEXT NULL DEFAULT NULL ,
  `STATUS` ENUM('WAITING','IN_PROGRESS','END_OK','END_WARNING','END_ERROR') NULL DEFAULT 'WAITING' ,
  `EXECUTION_ID` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `INSTIGATOR_ID` INT(11) NOT NULL ,
  `INSTIGATOR_EMAIL` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `DATE_INSERT` TIMESTAMP NULL DEFAULT NULL ,
  `DATE_START` TIMESTAMP NULL DEFAULT NULL ,
  `DATE_END` TIMESTAMP NULL DEFAULT NULL ,
  `LOG` TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`DEPLOY_QUEUE_ID`) ,
  INDEX `STATUS` (`STATUS` ASC) ,
  INDEX `DATE_INSERT` (`DATE_INSERT` ASC) ,
  INDEX `FK_DEPLOY_QUEUE_USER` (`INSTIGATOR_ID` ASC) ,
  INDEX `FK_DEPLOY_QUEUE_PROJECT` (`PROJECT_ID` ASC) ,
  INDEX `FK_DEPLOY_QUEUE_PROJECT_CONFIGURATION` (`PROJECT_CONFIGURATION_ID` ASC) ,
  CONSTRAINT `FK_DEPLOY_QUEUE_USER`
    FOREIGN KEY (`INSTIGATOR_ID` )
    REFERENCES `supervisor`.`EDE_USER` (`USER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEPLOY_QUEUE_PROJECT`
    FOREIGN KEY (`PROJECT_ID` )
    REFERENCES `supervisor`.`EDE_PROJECT` (`PROJECT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEPLOY_QUEUE_PROJECT_CONFIGURATION`
    FOREIGN KEY (`PROJECT_CONFIGURATION_ID` )
    REFERENCES `supervisor`.`EDE_PROJECT_CONFIGURATION` (`PROJECT_CONFIGURATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 352
DEFAULT CHARACTER SET = latin1;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;