#!/bin/sh

#Script to add TwengaBuild Number to TWENGABUILD Table

if [ "$#" != "1" ]; then
	echo "Usage: `basename $0` twengabuildnum" 2>&1
	exit 1;
fi

twengabuildnum=$1

type=`echo $twengabuildnum | cut -c 15`

if [ "$type" = "P" ]; then
	twengabuild_type="'PRODUCTION'";
fi
if [ "$type" = "I" ]; then
	twengabuild_type="'INTERNAL'";
fi
if [ "$type" = "Q" ]; then
	twengabuild_type="'QA'";
fi
if [ "$type" = "B" ]; then
	twengabuild_type="'BCT'";
fi

if [ "$twengabuild_type" = "" ]; then
	echo "twengabuildnum is invalid" 2>&1
	exit 1;
fi

twengabuildnum="'$twengabuildnum'";

source ~/.bash_twenga
#DEBUG="-vv"

loadDbEnv "master"

mysql $DEBUG -h "$TWENGA_DB_HOST" -u "$TWENGA_DB_USERNAME" --password="$TWENGA_DB_PASSWORD" $TWENGA_DB_DB 1>/dev/null 2>&1 << _eof
INSERT INTO TWENGABUILD VALUES ( $twengabuildnum , NOW(), $twengabuild_type );
_eof

exit 0

