#!/bin/sh

source $HOME/.bash_twenga
source $HOME/twenga/tools/master_synchro.cfg
source $HOME/twenga/tools/lb_twenga.cfg
HACLUSTER="/home/prod/twenga/tools/haproxycluster"
SSH_CONNECT_TIMEOUT="-oConnectTimeout=30"

usage="wwwX Enable|Disable [geozone]";

if ( [ "$#" != "2" ] && [ "$#" != "3" ] ); then
	echo "Usage: `basename $0` $usage" 1>&2
	exit 1;
fi

TMPFILE="/home/tmp/.wwwcluster_$!"

webserver=$1
if [ "`echo $webserver | cut -c 1`" != "w" ]; then
	webserver=www$webserver
fi
mode=$2
geozone=$3

if ( [ "$mode" != "Enable" ] && [ "$mode" != "Disable" ] && [ "$mode" != "D" ] && [ "$mode" != "E" ] && [ "$mode" != "d" ] && [ "$mode" != "e" ] ); then
	    echo "Usage: `basename $0` $usage" 1>&2
	    exit 1;
fi

if ( [ "$mode" = "D" ] || [ "$mode" = "d" ] ); then
	mode="Disable"
fi
if ( [ "$mode" = "E" ] || [ "$mode" = "e" ] ); then
	mode="Enable"
fi

if [ "$geozone" = "" ]; then # Disable server for all geozone
	all_geozone=`getAllGeozoneForServer $webserver`
else
	all_geozone="$geozone"
fi

if [ "`echo $webserver | cut -c 1-7`" = "wwwtest" ]; then
	echo "$webserver : Sucessfull switch to $mode for geozones $all_geozone (Not in cluster).";
	exit 0
fi

function updateBalancers
{
	fail=0

	for zgeozone in $all_geozone;
	do
		gz=`echo $zgeozone | awk '{print toupper($1)}'`
		websites=`declare -p "WEBSITES_FRONT_$gz" 2>/dev/null | awk -F '"' '{print $2}'`
		website=`echo $websites | tr ' ' '\n' | grep "^www"`
		ctrlfiles="$ctrlfiles /usr/local/apache2/htdocs/check_${zgeozone}.html"
	done

	if [ "$auto_cluster_disable" = "1" ]; then
		if [ "$mode" = "Disable" ]; then
			ssh -tt $webserver "rm -f $ctrlfiles 1>/dev/null" 1>$TMPFILE 2>&1
			rc1=$?
		fi
		if [ "$mode" = "Enable" ]; then
			ssh -tt $webserver "touch $ctrlfiles 1>/dev/null" 1>$TMPFILE 2>&1
			rc1=$?
		fi
	else
		rc1=0
		for zgeozone in $all_geozone;
		do
			gz=`echo $zgeozone | awk '{print toupper($1)}'`
			websites=`declare -p "WEBSITES_FRONT_$gz" 2>/dev/null | awk -F '"' '{print $2}'`
			website=`echo $websites | tr ' ' '\n' | grep "^www"`
			if [ "$website" = "" ]; then
                continue;
            fi
			lower_mode=`echo $mode | awk '{print tolower($1)}'`
			#IPs=`getIpForWebsite $zgeozone`
			#for IP in $IPs;
			getLbInfo web $zgeozone
			for IP in $IP_LB;
			do
				$HACLUSTER $IP $lower_mode $website $webserver web 1>$TMPFILE 2>&1
				rc1=$((${rc1} + $?))
			done
		done
	fi

	 if [ "$rc1" = "0" ]; then
		echo "$webserver : Sucessfull switch to $mode for geozones $all_geozone.";
		if [ "$mode" = "Disable" ]; then
			sleep 2
		fi
	else
		echo "$webserver : Unable to switch to $mode for geozones $all_geozone!";	
		if [ -s $TMPFILE ]; then
			cat $TMPFILE
		fi
		fail=1
	fi

	rm -f $TMPFILE 1>&2 2>/dev/null

	return $fail
}

hasUs=`echo "$all_geozone" | grep "us"`
if ( [ "$hasUs" ] && [ "$TWENGA_DC" != "US" ] ); then
	ssh $SSH_CONNECT_TIMEOUT $SERVER_MONITORING_US "~/twenga/tools/wwwcluster $@"
else
	updateBalancers
fi
rc=$?
exit $rc

